apiVersion: v1
kind: Namespace
metadata:
  name: c2c-azure-metaage-chihung-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-azure-metaage-chihung-deployment
  namespace: c2c-azure-metaage-chihung-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:bf6f05708bc32a54a90430f24023fa366fe0b091

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-azure-metaage-chihung-label
  name: c2c-azure-metaage-chihung-service
  namespace: c2c-azure-metaage-chihung-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---